### ISSUE TITLE
Possible error in the tutorial

### ISSUE THREAD

**Issue by a39172** [FIWARE/tutorials.IoT-Agent-JSON#8]
Is this PATCH request to the IoT agent possible? Does the IoT agent have such an endpoint?

- `curl -L -X PATCH 'http://localhost:4041/ngsi-ld/v1/entities/urn:ngsi-ld:Device:water001/attrs/on'`

**Comment by jason-fox** [comment]
If the IoT Agent is running in NGSI-LD or "mixed" modes, then the router will set up a listener for actuation requests, you can find the code here: see [contextServer-NGSI-LD.js#L48](https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/northBound/contextServer-NGSI-LD.js#L48)

If you are running an IoT Agent in NGSI-v2 mode, the endpoint won't be serviced.
